; (add-hook 'haskell-mode-hook 'turn-on-haskell-doc-mode)
; (add-hook 'haskell-mode-hook 'turn-on-haskell-indent)
; (add-hook 'haskell-mode-hook 'font-lock-mode)
; (add-hook 'haskell-mode-hook 'imenu-add-menubar-index)

(add-hook 'haskell-mode-hook
	  (lambda ()
	    (turn-on-haskell-indentation)
	    ;; (interactive-haskell-mode)
	    (set (make-local-variable 'dabbrev-case-fold-search) nil)
	    (set-face-foreground 'font-lock-type-face "PaleGreen")
	    (set-face-foreground 'font-lock-function-name-face "LightSkyBlue")
	    (define-key haskell-mode-map (kbd "C-c a")
	      'HASKELL-CUSTOM:align-record-or-type-signature)
	    ))
